language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  -provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo setting에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

  bucket: junyoung-springboot-build # S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: private # zip 파일접근을 private으로
  local_dir: deploy # befroe_deploy에서 생성한 디렉토리
  wait-until-deployed: true


# Travis CI(지속적인 통합) Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


# CI 실행 완료 시 메일로 알람

notifications:
  email:
    recipients:
      - a79007714@gmail.com
